language: node_js
sudo: false
node_js:
- '0.12'
notifications:
  slack:
    secure: iKqoDt5ipGK+C9GAn4BXcZhtNGkeT/KV0eWl0vbaLmhOg5JZO2A4h3XF6sSp/Sy4upNDXz9ZaEtsKAeK7Xbe5kX5sakCmI7+dc4XrOuGppem8wkn3ioybkDT2i2wcIa5n+DNIFNJOBt6s8wvHMSfGdKw0QyUxf5H/VAENp9BV+g=
